-- Migración 106: catálogo de productos de súper, editable a mano.
--
-- Hasta ahora el catálogo del selector "Elegir del catálogo" (Casa) era
-- una lista fija en el código. Esta migración lo pasa a una tabla, con
-- los mismos ~130 productos ya cargados, para que después se puedan
-- agregar productos nuevos desde la propia pantalla sin tocar código.
--
-- Copiar y pegar en Supabase → SQL Editor → Run.

create table if not exists catalogo_productos_super (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  grupo text not null,
  categoria text not null
    check (categoria in ('Alimentos', 'Limpieza', 'Higiene y perfumería', 'Electrodomésticos', 'Herramientas', 'Otros')),
  unidad text,
  created_at timestamptz not null default now()
);

alter table catalogo_productos_super enable row level security;
drop policy if exists duena_todo on catalogo_productos_super;
create policy duena_todo on catalogo_productos_super for all using (es_duena()) with check (es_duena());

insert into catalogo_productos_super (nombre, grupo, categoria, unidad) values
  ('Banana', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Manzana', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Naranja', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Mandarina', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Pera', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Frutilla', 'Frutas y verduras', 'Alimentos', 'bandeja'),
  ('Limón', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Palta', 'Frutas y verduras', 'Alimentos', 'unidades'),
  ('Papa', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Batata', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Cebolla', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Tomate', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Zapallo', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Zanahoria', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Zapallito', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Lechuga', 'Frutas y verduras', 'Alimentos', 'unidades'),
  ('Acelga', 'Frutas y verduras', 'Alimentos', 'atado'),
  ('Espinaca', 'Frutas y verduras', 'Alimentos', 'atado'),
  ('Morrón', 'Frutas y verduras', 'Alimentos', 'unidades'),
  ('Ajo', 'Frutas y verduras', 'Alimentos', 'unidades'),
  ('Choclo', 'Frutas y verduras', 'Alimentos', 'unidades'),
  ('Berenjena', 'Frutas y verduras', 'Alimentos', 'kg'),
  ('Leche', 'Lácteos y huevos', 'Alimentos', 'litros'),
  ('Yogur', 'Lácteos y huevos', 'Alimentos', 'unidades'),
  ('Queso cremoso', 'Lácteos y huevos', 'Alimentos', 'kg'),
  ('Queso rallado', 'Lácteos y huevos', 'Alimentos', 'paquete'),
  ('Queso en fetas', 'Lácteos y huevos', 'Alimentos', 'paquete'),
  ('Manteca', 'Lácteos y huevos', 'Alimentos', 'unidades'),
  ('Crema de leche', 'Lácteos y huevos', 'Alimentos', 'unidades'),
  ('Huevos', 'Lácteos y huevos', 'Alimentos', 'maple'),
  ('Postre / flan', 'Lácteos y huevos', 'Alimentos', 'unidades'),
  ('Dulce de leche', 'Lácteos y huevos', 'Alimentos', 'unidades'),
  ('Carne picada', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Asado', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Bife de chorizo', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Milanesas', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Pollo', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Suprema de pollo', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Pescado', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Jamón cocido', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Salchichas', 'Carnes, pollo y pescado', 'Alimentos', 'paquete'),
  ('Panceta', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Chorizo', 'Carnes, pollo y pescado', 'Alimentos', 'kg'),
  ('Pan', 'Panadería y cereales', 'Alimentos', 'kg'),
  ('Pan lactal', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Facturas', 'Panadería y cereales', 'Alimentos', 'unidades'),
  ('Galletitas dulces', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Galletitas de agua', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Arroz', 'Panadería y cereales', 'Alimentos', 'kg'),
  ('Fideos', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Harina', 'Panadería y cereales', 'Alimentos', 'kg'),
  ('Avena', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Cereales', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Polenta', 'Panadería y cereales', 'Alimentos', 'paquete'),
  ('Aceite', 'Almacén y conservas', 'Alimentos', 'litros'),
  ('Vinagre', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Sal', 'Almacén y conservas', 'Alimentos', 'paquete'),
  ('Azúcar', 'Almacén y conservas', 'Alimentos', 'kg'),
  ('Edulcorante', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Yerba mate', 'Almacén y conservas', 'Alimentos', 'kg'),
  ('Café', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Té', 'Almacén y conservas', 'Alimentos', 'caja'),
  ('Mayonesa', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Ketchup', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Mostaza', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Salsa de tomate', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Puré de tomate', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Atún en lata', 'Almacén y conservas', 'Alimentos', 'lata'),
  ('Arvejas en lata', 'Almacén y conservas', 'Alimentos', 'lata'),
  ('Choclo en lata', 'Almacén y conservas', 'Alimentos', 'lata'),
  ('Legumbres (lentejas/porotos)', 'Almacén y conservas', 'Alimentos', 'paquete'),
  ('Caldo en cubitos', 'Almacén y conservas', 'Alimentos', 'caja'),
  ('Mermelada', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Miel', 'Almacén y conservas', 'Alimentos', 'unidades'),
  ('Agua mineral', 'Bebidas', 'Alimentos', 'litros'),
  ('Agua saborizada', 'Bebidas', 'Alimentos', 'litros'),
  ('Gaseosa', 'Bebidas', 'Alimentos', 'litros'),
  ('Jugo exprimido / en polvo', 'Bebidas', 'Alimentos', 'unidades'),
  ('Cerveza', 'Bebidas', 'Alimentos', 'unidades'),
  ('Vino', 'Bebidas', 'Alimentos', 'unidades'),
  ('Soda', 'Bebidas', 'Alimentos', 'unidades'),
  ('Papas fritas congeladas', 'Congelados', 'Alimentos', 'paquete'),
  ('Vegetales congelados', 'Congelados', 'Alimentos', 'paquete'),
  ('Hamburguesas congeladas', 'Congelados', 'Alimentos', 'caja'),
  ('Tapas de empanadas', 'Congelados', 'Alimentos', 'paquete'),
  ('Helado', 'Congelados', 'Alimentos', 'unidades'),
  ('Detergente', 'Limpieza', 'Limpieza', 'unidades'),
  ('Lavandina', 'Limpieza', 'Limpieza', 'unidades'),
  ('Limpiador de pisos', 'Limpieza', 'Limpieza', 'unidades'),
  ('Limpiavidrios', 'Limpieza', 'Limpieza', 'unidades'),
  ('Esponjas', 'Limpieza', 'Limpieza', 'paquete'),
  ('Papel de cocina', 'Limpieza', 'Limpieza', 'rollo'),
  ('Rollo de cocina', 'Limpieza', 'Limpieza', 'rollo'),
  ('Bolsas de residuo', 'Limpieza', 'Limpieza', 'paquete'),
  ('Jabón en polvo / líquido para ropa', 'Limpieza', 'Limpieza', 'unidades'),
  ('Suavizante para ropa', 'Limpieza', 'Limpieza', 'unidades'),
  ('Lustramuebles', 'Limpieza', 'Limpieza', 'unidades'),
  ('Desodorante de ambiente', 'Limpieza', 'Limpieza', 'unidades'),
  ('Insecticida', 'Limpieza', 'Limpieza', 'unidades'),
  ('Guantes de goma', 'Limpieza', 'Limpieza', 'par'),
  ('Trapo de piso', 'Limpieza', 'Limpieza', 'unidades'),
  ('Papel higiénico', 'Higiene y perfumería', 'Higiene y perfumería', 'rollo'),
  ('Jabón de tocador', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Shampoo', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Acondicionador', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Crema corporal', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Desodorante', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Pasta dental', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Cepillo de dientes', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Hilo dental', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Algodón', 'Higiene y perfumería', 'Higiene y perfumería', 'paquete'),
  ('Hisopos', 'Higiene y perfumería', 'Higiene y perfumería', 'paquete'),
  ('Toallitas húmedas', 'Higiene y perfumería', 'Higiene y perfumería', 'paquete'),
  ('Toallas femeninas', 'Higiene y perfumería', 'Higiene y perfumería', 'paquete'),
  ('Máquina de afeitar / repuestos', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades'),
  ('Protector solar', 'Higiene y perfumería', 'Higiene y perfumería', 'unidades')
on conflict (nombre) do nothing;
