// Datos de prueba (todavía no vienen de una base de datos real).
// Sirven para ver la grilla funcionando mientras conectamos Supabase.

export const turnosDeEjemplo = [
  {
    id: 1,
    horaInicio: "08:00",
    duracionMin: 30,
    consultorio: 1,
    paciente: "Lucía Fernández",
    profesionalDeTurno: "Dra. Gómez",
    tipoAtencion: "Consulta",
    cobertura: "Particular",
    estado: "Agendado",
    confirmacion: "Confirmado",
    presencia: "Pendiente",
    asistencia: "Pendiente",
  },
  {
    id: 2,
    horaInicio: "08:30",
    duracionMin: 90,
    consultorio: 2,
    paciente: "Martín Sosa",
    profesionalDeTurno: "Dr. Pérez",
    tipoAtencion: "Tratamiento",
    cobertura: "OSDE",
    estado: "Agendado",
    confirmacion: "Sin confirmar",
    presencia: "En consultorio",
    asistencia: "Pendiente",
  },
  {
    id: 3,
    horaInicio: "09:00",
    duracionMin: 30,
    consultorio: 3,
    paciente: "Carla Díaz",
    profesionalDeTurno: "Dra. Gómez",
    tipoAtencion: "Urgencia",
    cobertura: "Particular",
    estado: "Agendado",
    confirmacion: "No responde",
    presencia: "Pendiente",
    asistencia: "Pendiente",
  },
  {
    id: 4,
    horaInicio: "10:00",
    duracionMin: 30,
    consultorio: 1,
    paciente: "Jorge Aguirre",
    profesionalDeTurno: "Dr. Pérez",
    tipoAtencion: "Control",
    cobertura: "IAPOS",
    estado: "Reprogramado",
    confirmacion: "Reprogramar",
    presencia: "Pendiente",
    asistencia: "Pendiente",
  },
  {
    id: 5,
    horaInicio: "11:00",
    duracionMin: 30,
    consultorio: 1,
    paciente: "Sofía Britos",
    profesionalDeTurno: "Dra. Gómez",
    tipoAtencion: "Primera consulta",
    cobertura: "Particular",
    estado: "Agendado",
    confirmacion: "Confirmado",
    presencia: "Finalizado",
    asistencia: "Asistió",
  },
  {
    id: 6,
    horaInicio: "12:00",
    duracionMin: 30,
    consultorio: 2,
    paciente: "Nicolás Ríos",
    profesionalDeTurno: "Dr. Pérez",
    tipoAtencion: "Consulta",
    cobertura: "Particular",
    estado: "Agendado",
    confirmacion: "Confirmado",
    presencia: "Pendiente",
    asistencia: "No asistió",
  },
];
